on:
  issue_comment:

env:
  TARGET_REPO_OWNER: 'cupy'
  TARGET_REPO_NAME: 'self-hosted-ci'

jobs:
  dispatch:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'cupy'
    steps:
    - name: Generate Token
      id: generate-token
      uses: actions/create-github-app-token@v1
      with:
        app-id: ${{ vars.GH_APP_SELF_HOSTED_CI_ID }}
        private-key: ${{ secrets.GH_APP_SELF_HOSTED_CI_PEM }}
        owner: ${{ env.TARGET_REPO_OWNER }}
        repositories: ${{ env.TARGET_REPO_NAME }}
    - name: Dispach CI
      uses: peter-evans/repository-dispatch@v3
      with:
        repository: ${{ env.TARGET_REPO_OWNER }}/${{ env.TARGET_REPO_NAME }}
        event-type: rocm-ci
        token: ${{ steps.generate-token.outputs.token }}
        client-payload: |
          {
            "sha": "451140c6fa15d2c1bee4dda49a769563136142e8"
          }
